name: CI/CD - Validator Reward Contract

on:
  push:
    paths:
      - 'validator_reward_contract/**' 
    branches:
      - main
  pull_request:
    paths:
      - 'validator_reward_contract/**'
    branches:
      - main

jobs:
  build-and-test:
    name: Build & Test Contract
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rust-src, rustfmt, clippy

      - name: Install ink! CLI
        run: |
          cargo install --force cargo-contract

      - name: Install Substrate Dependencies
        run: |
          sudo apt update && sudo apt install -y \
          cmake clang pkg-config libssl-dev \
          libudev-dev protobuf-compiler

      - name: Build Validator Reward Contract
        run: |
          cd validator_reward_contract
          cargo contract build --release  

      - name: Run Tests
        run: |
          cd validator_reward_contract
          cargo test --all
